version: 0
metadata:
    name: 'OpenCloudConfig'
    description: 'OpenCloudConfig CI Tasks'
    owner: '{{event.head.user.email}}'
    source: '{{event.head.repo.url}}'
tasks:
    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.validation'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - pull_request.*
                  - push
      payload:
          maxRunTime: 600
          image: 'grenade/opencloudconfig'
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && cd OpenCloudConfig && git checkout {{event.head.repo.branch}} && echo "do lint stuff here"'
      metadata:
          name: 'Validate submission'
          description: 'run a linter against json and powershell files'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-L-b-win2012
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-L-b-win2012'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
      payload:
          maxRunTime: 7200
          image: 'grenade/opencloudconfig'
          features:
            taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && cd OpenCloudConfig && git checkout {{event.head.repo.branch}} && ci/update-workertype.sh gecko-L-b-win2012'
      metadata:
          name: 'Update gecko-L-b-win2012 AMIs'
          description: 'recreate base worker type AMIs which use OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-L-t-win7-32
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-L-t-win7-32'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
      payload:
          maxRunTime: 7200
          image: 'grenade/opencloudconfig'
          features:
            taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && cd OpenCloudConfig && git checkout {{event.head.repo.branch}} && ci/update-workertype.sh gecko-L-t-win7-32'
      metadata:
          name: 'Update gecko-L-t-win7-32 AMIs'
          description: 'recreate base worker type AMIs which use OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'
