version: 0
metadata:
    name: 'OpenCloudConfig'
    description: 'OpenCloudConfig CI Tasks'
    owner: '{{event.head.user.email}}'
    source: '{{event.head.repo.url}}'
tasks:
    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      routes:
          - 'index.garbage.opencloudconfig.v1.revision.{{event.head.sha}}.validation'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - pull_request.*
                  - push
      payload:
          maxRunTime: 600
          image: 'grenade/opencloudconfig'
          command:
              - 'git clone {{event.head.repo.url}} && cd OpenCloudConfig && git checkout {{event.head.repo.branch}} && echo "do lint stuff here"'
      metadata:
          name: 'Validate submission'
          description: 'run a linter against json and powershell files'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      routes:
          - 'index.garbage.opencloudconfig.v1.revision.{{event.head.sha}}.ami'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
      payload:
          maxRunTime: 7200
          image: 'grenade/opencloudconfig'
          command:
              - 'git clone {{event.head.repo.url}} && cd OpenCloudConfig && git checkout {{event.head.repo.branch}} && echo "do ami creation stuff here"'
      metadata:
          name: 'Update OpenCloudConfig AMIs'
          description: 'recreate base worker type AMIs which use OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'