version: 0
metadata:
    name: 'OpenCloudConfig'
    description: 'OpenCloudConfig CI Tasks'
    owner: '{{event.head.user.email}}'
    source: '{{event.head.repo.url}}'
tasks:
    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.validation'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - pull_request.*
                  - push
          data:
              base:
                  sha: '{{event.base.sha}}'
                  user:
                      login: '{{event.base.user.login}}'
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 600
          image: 'grenade/opencloudconfig'
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && cd OpenCloudConfig && git checkout {{event.head.repo.branch}} && echo "do lint stuff here" && echo "taskGroupId: {{taskcluster.docker.taskGroupId}}"'
      metadata:
          name: 'Validate submission'
          description: 'run a linter against json and powershell files'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-1-b-win2012
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-1-b-win2012'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
          data:
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 10800
          image: 'grenade/opencloudconfig'
          features:
              taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && ./OpenCloudConfig/ci/update-workertype.sh gecko-1-b-win2012'
          artifacts:
              'project/releng/opencloudconfig/update-request.json':
                  type: file
                  path: './gecko-1-b-win2012.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/update-response.json':
                  type: file
                  path: './update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/secret-update-response.json':
                  type: file
                  path: './secret-update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/gecko-1-b-win2012.diff':
                  type: file
                  path: './gecko-1-b-win2012.diff'
                  expires: "{{ '1 year' | $fromNow }}"
      metadata:
          name: 'Update gecko-1-b-win2012 AMIs'
          description: 'recreate Firefox Windows try build AMIs using OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-3-b-win2012
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-3-b-win2012'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
          data:
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 10800
          image: 'grenade/opencloudconfig'
          features:
              taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && ./OpenCloudConfig/ci/update-workertype.sh gecko-3-b-win2012'
          artifacts:
              'project/releng/opencloudconfig/update-request.json':
                  type: file
                  path: './gecko-3-b-win2012.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/update-response.json':
                  type: file
                  path: './update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/secret-update-response.json':
                  type: file
                  path: './secret-update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/gecko-3-b-win2012.diff':
                  type: file
                  path: './gecko-3-b-win2012.diff'
                  expires: "{{ '1 year' | $fromNow }}"
      metadata:
          name: 'Update gecko-3-b-win2012 AMIs'
          description: 'recreate Firefox Windows prod build AMIs using OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-1-t-win7-32
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-1-t-win7-32'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
          data:
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 10800
          image: 'grenade/opencloudconfig'
          features:
              taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && ./OpenCloudConfig/ci/update-workertype.sh gecko-1-t-win7-32'
          artifacts:
              'project/releng/opencloudconfig/update-request.json':
                  type: file
                  path: './gecko-1-t-win7-32.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/update-response.json':
                  type: file
                  path: './update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/secret-update-response.json':
                  type: file
                  path: './secret-update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/gecko-1-t-win7-32.diff':
                  type: file
                  path: './gecko-1-t-win7-32.diff'
                  expires: "{{ '1 year' | $fromNow }}"
      metadata:
          name: 'Update gecko-1-t-win7-32 AMIs'
          description: 'recreate Firefox Windows 7 (32 bit) try test AMIs using OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-3-t-win7-32
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-3-t-win7-32'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
          data:
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 10800
          image: 'grenade/opencloudconfig'
          features:
              taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && ./OpenCloudConfig/ci/update-workertype.sh gecko-3-t-win7-32'
          artifacts:
              'project/releng/opencloudconfig/update-request.json':
                  type: file
                  path: './gecko-3-t-win7-32.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/update-response.json':
                  type: file
                  path: './update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/secret-update-response.json':
                  type: file
                  path: './secret-update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/gecko-3-t-win7-32.diff':
                  type: file
                  path: './gecko-3-t-win7-32.diff'
                  expires: "{{ '1 year' | $fromNow }}"
      metadata:
          name: 'Update gecko-3-t-win7-32 AMIs'
          description: 'recreate Firefox Windows 7 (32 bit) prod test AMIs using OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-1-t-win10-64
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-1-t-win10-64'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
          data:
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 10800
          image: 'grenade/opencloudconfig'
          features:
              taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && ./OpenCloudConfig/ci/update-workertype.sh gecko-1-t-win10-64'
          artifacts:
              'project/releng/opencloudconfig/update-request.json':
                  type: file
                  path: './gecko-1-t-win10-64.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/update-response.json':
                  type: file
                  path: './update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/secret-update-response.json':
                  type: file
                  path: './secret-update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/gecko-1-t-win10-64.diff':
                  type: file
                  path: './gecko-1-t-win10-64.diff'
                  expires: "{{ '1 year' | $fromNow }}"
      metadata:
          name: 'Update gecko-1-t-win10-64 AMIs'
          description: 'recreate Firefox Windows 10 (64 bit) try test AMIs using OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'

    - provisionerId: '{{taskcluster.docker.provisionerId}}'
      scopes:
          - secrets:get:repo:github.com/mozilla-releng/OpenCloudConfig:updateworkertype
          - aws-provisioner:manage-worker-type:gecko-3-t-win10-64
      routes:
          - 'index.project.releng.opencloudconfig.v1.revision.{{event.head.sha}}.gecko-3-t-win10-64'
      workerType: '{{taskcluster.docker.workerType}}'
      extra:
          github:
              env: true
              events:
                  - push
              branches:
                - master
          data:
              head:
                  sha: '{{event.head.sha}}'
                  user:
                      email: '{{event.head.user.email}}'
      payload:
          maxRunTime: 10800
          image: 'grenade/opencloudconfig'
          features:
              taskclusterProxy: true
          command:
              - '/bin/bash'
              - '--login'
              - '-c'
              - 'git clone --quiet {{event.head.repo.url}} && ./OpenCloudConfig/ci/update-workertype.sh gecko-3-t-win10-64'
          artifacts:
              'project/releng/opencloudconfig/update-request.json':
                  type: file
                  path: './gecko-3-t-win10-64.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/update-response.json':
                  type: file
                  path: './update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/secret-update-response.json':
                  type: file
                  path: './secret-update-response.json'
                  expires: "{{ '4 hours' | $fromNow }}"
              'project/releng/opencloudconfig/gecko-3-t-win10-64.diff':
                  type: file
                  path: './gecko-3-t-win10-64.diff'
                  expires: "{{ '1 year' | $fromNow }}"
      metadata:
          name: 'Update gecko-3-t-win10-64 AMIs'
          description: 'recreate Firefox Windows 10 (64 bit) prod test AMIs using OpenCloudConfig for configuration and dependency installation'
          owner: '{{event.head.user.email}}'
          source: '{{event.head.repo.url}}'
